# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f583fdb9bf1fc88589a123ed9042544bf4136ea72958ca102ecf1feb00839d87f8dbaedade2f2903737f3f09f72221a5fab00a1ff1c8a56607f184dd20945aa

test:
  secret_key_base: c857542d823fa36e810b96c04eacfe121f2720ee9997f3f9f7990693af2081df8870ca509c3b6eb64cc93fb2aa6b44b44fd2945420743f994124ba13d6e2a1bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
